//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.05 at 08:37:55 PM EEST 
//


package ua.epam.tariff;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.xml.bind.annotation.*;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "plan"
})
@XmlRootElement(name = "tariff")
public class Tariff {

    protected List<Plan> plan = new ArrayList<>();

    public List<Plan> getPlan() {
        if (plan == null) {
            plan = new ArrayList<>();
        }

        return this.plan;
    }

    @Override
    public String toString() {

        Collections.sort(plan, new TariffComparator());
        StringBuilder stringBuilder = new StringBuilder();

        for (Tariff.Plan p : plan) {
            stringBuilder.append(p + "\n------\n");
        }

        return "Tariff:\n------\n" + stringBuilder;
    }

  @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "operatorName",
        "payroll",
        "callPrices",
        "smsPrice",
        "parameters"
    })
    public static class Plan {

        @XmlElement(name = "operator-name", required = true)
        protected String operatorName;

        @XmlElement(name = "payroll", required = true)
        protected double payroll;

        @XmlElement(name = "call-prices", required = true)
        protected CallPrices callPrices = new CallPrices();

        @XmlElement(name = "sms-price", required = true)
        protected double smsPrice;

        @XmlElement(name = "parameters", required = true)
        protected Parameters parameters = new Parameters();

        @XmlAttribute(name = "name", required = true)
        protected String name;

        @XmlAttribute(name = "planID", required = true)
        protected int planID;

        public String getOperatorName() {
            return operatorName;
        }

        public void setOperatorName(String value) {
            this.operatorName = value;
        }

        public double getPayroll() {
            return payroll;
        }

        public void setPayroll(double value) {
            this.payroll = value;
        }

        public CallPrices getCallPrices() {
            return callPrices;
        }

        public void setCallPrices(CallPrices value) {
            this.callPrices = value;
        }

        public double getSmsPrice() {
            return smsPrice;
        }

        public void setSmsPrice(double value) {
            this.smsPrice = value;
        }

        public Parameters getParameters() {
            return parameters;
        }

        public void setParameters(Parameters value) {
            this.parameters = value;
        }

        public String getName() {
            return name;
        }

        public void setName(String value) {
            this.name = value;
        }

        public int getPlanID() {
            return planID;
        }

        public void setPlanID(int value) {
            this.planID = value;
        }

        @Override
        public String toString() {
            return "Plan\n" +
                    "Name: " + name +
                    ", ID: " + planID +
                    ", Operator: " + operatorName +
                    ", Payroll: " + payroll +
                    ", SMS price: " + smsPrice +
                    '\n' + callPrices +
                    '\n' + parameters;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "insideNetCalls",
            "outsideNetCalls",
            "stationaryPhoneCalls"
        })
        public static class CallPrices {

            @XmlElement(name = "inside-net-calls", required = true)
            protected double insideNetCalls;

            @XmlElement(name = "outside-net-calls", required = true)
            protected double outsideNetCalls;

            @XmlElement(name = "stationary-phone-calls", required = true)
            protected double stationaryPhoneCalls;

            public double getInsideNetCalls() {
                return insideNetCalls;
            }

            public void setInsideNetCalls(double value) {
                this.insideNetCalls = value;
            }

            public double getOutsideNetCalls() {
                return outsideNetCalls;
            }

            public void setOutsideNetCalls(double value) {
                this.outsideNetCalls = value;
            }

            public double getStationaryPhoneCalls() {
                return stationaryPhoneCalls;
            }

            public void setStationaryPhoneCalls(double value) {
                this.stationaryPhoneCalls = value;
            }

            @Override
            public String toString() {
                return "Call prices:" +
                        "\n\t-calls inside net: " + insideNetCalls +
                        "\n\t-calls outside net: " + outsideNetCalls +
                        "\n\t-calls to stationary phones: " + stationaryPhoneCalls;
            }
        }

     @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "favouriteNumber",
            "billing",
            "activationPrice"
        })
        public static class Parameters {

            @XmlElement(name = "favourite-number")
            protected FavouriteNumber favouriteNumber = new FavouriteNumber();

            @XmlElement(name = "billing", required = true)
            protected String billing;

            @XmlElement(name = "activation-price", required = true)
            protected double activationPrice;

            public FavouriteNumber getFavouriteNumber() {
                return favouriteNumber;
            }

            public void setFavouriteNumber(FavouriteNumber value) {
                this.favouriteNumber = value;
            }

            public String getBilling() {
                return billing;
            }

            public void setBilling(String value) {
                this.billing = value;
            }

            public double getActivationPrice() {
                return activationPrice;
            }

             public void setActivationPrice(double value) {
                this.activationPrice = value;
            }

            @Override
            public String toString() {
                return "Parameters:" +
                        "\n\t-" + favouriteNumber +
                        "\n\t-billing: " + billing +
                        "\n\t-activation price: " + activationPrice;
            }

            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "value"
            })
            public static class FavouriteNumber {

                @XmlValue
                protected int value;

                @XmlAttribute(name = "numbers-amount", required = true)
                protected int numbersAmount;

                public int getValue() {
                    return value;
                }

                public void setValue(int value) {
                    this.value = value;
                }

                public int getNumbersAmount() {
                    return numbersAmount;
                }

                public void setNumbersAmount(int value) {
                    this.numbersAmount = value;
                }

                @Override
                public String toString() {
                    return "favourite number service (" +
                            "price: " + value +
                            ", numbers amount: " + numbersAmount + ")";
                }
            }
        }
    }
}
